import { motion, useInView, AnimatePresence } from 'framer-motion';
import { useRef, useState } from 'react';
import {
  ExternalLink, Github, Folder, ArrowUpRight, Sparkles, Globe, Shield,
  Cpu, Database, Box, AlertTriangle, BarChart3, Server, Microscope,
  ChevronDown, Layers, Terminal, Brain
} from 'lucide-react';
import { GlassCard } from '../hooks/useGlassTilt';

/* ============================================================
   FLAGSHIP CASE STUDIES
   ============================================================ */

const flagshipProjects = [
  {
    id: 'onyx',
    title: 'OnyxBrowser v2.0',
    subtitle: 'The Agentic Web Engine',
    description:
      'A natively compiled, AI-first desktop web browser that replaces the standard URL bar with an Agentic Omnibox. It leverages local LLMs for DOM automation, vector memory for semantic history search, and a custom IPC bridge connecting Electron to a frozen Python backend.',
    stack: ['React', 'Electron', 'Python', 'FastAPI', 'ChromaDB', 'PyInstaller', 'LLMs'],
    github: 'https://github.com/etk18/OnyxBrowser',
    live: 'https://onyxbrowser.vercel.app/',
    accent: 'onyx',
    icon: Globe,
    highlights: [
      {
        icon: Cpu,
        title: 'Agentic DOM Automation',
        detail:
          'Extracts token-efficient Spatial DOM Maps and routes them through local LLMs to physically execute native browser interactions (e.g., /click, /summarize).',
      },
      {
        icon: Database,
        title: 'Semantic Vector Memory',
        detail:
          'Passively vectorizes web history into a local ChromaDB, allowing natural language search of past browsing sessions via a custom onyx://memory protocol.',
      },
      {
        icon: Box,
        title: 'Standalone Bundling & IPC',
        detail:
          'Built a custom IPC bridge connecting the Node.js Main Process to a Python/FastAPI backend frozen via PyInstaller into a standalone machine-code binary.',
      },
      {
        icon: AlertTriangle,
        title: 'Graceful Degradation',
        detail:
          'Engineered OS-level error handling to catch asynchronous ENOENT spawn failures, allowing the app to fall back to a blazing-fast standard browser if the AI binary is unmatched across OS builds.',
      },
    ],
  },
  {
    id: 'sentinel',
    title: 'Spectral Sentinel',
    subtitle: 'AI/ML Deepfake Detection',
    description:
      'A high-performance AI/ML application engineered for the rapid detection and classification of deepfake images. It combines a robust FastAPI backend with a sophisticated ML classification pipeline to identify synthetic artifacts generated by modern generative AI models.',
    stack: ['Python', 'FastAPI', 'Machine Learning', 'Computer Vision'],
    github: 'https://github.com/etk18/SpectralSentinal',
    live: 'https://etk18-spectralsentinal.vercel.app/',
    accent: 'sentinel',
    icon: Shield,
    highlights: [
      {
        icon: BarChart3,
        title: 'Data Pipeline',
        detail:
          'Managed and processed the massive ArtiFact dataset, organizing complex image file structures for optimal model training and evaluation.',
      },
      {
        icon: Server,
        title: 'API Architecture',
        detail:
          'Deployed a robust FastAPI backend to handle high-throughput image processing, routing user uploads through the ML classification pipeline with minimal latency.',
      },
      {
        icon: Microscope,
        title: 'Detection Engine',
        detail:
          'Engineered the inference logic to accurately identify synthetic artifacts generated by modern generative AI models.',
      },
    ],
  },
];

/* ============================================================
   OTHER PROJECTS
   ============================================================ */

const otherProjects = [
  {
    title: 'Crypto Price Prediction Model',
    description:
      'Deep learning model using LSTM neural networks to predict cryptocurrency price movements with time-series data analysis. Analyzed 50,000+ data points.',
    tags: ['Python', 'TensorFlow', 'Keras', 'Pandas', 'LSTM'],
    github: 'https://github.com/etk18',
    category: 'AI/ML',
    status: 'In Progress',
  },
  {
    title: 'Instagram Clone',
    description:
      'Full-featured social media platform with user authentication, profile management, real-time interactions, and dynamic newsfeed.',
    tags: ['React.js', 'Node.js', 'MongoDB', 'Express.js'],
    github: 'https://github.com/etk18',
    category: 'Full Stack',
  },
  {
    title: 'NLP Text Pipeline',
    description: 'End-to-end NLP pipeline for text classification and sentiment analysis using transformers.',
    tags: ['Python', 'PyTorch', 'NLP', 'Transformers'],
    github: 'https://github.com/etk18',
    category: 'AI/ML',
  },
  {
    title: 'Data Visualization Dashboard',
    description: 'Interactive dashboard for visualizing complex datasets with dynamic charts.',
    tags: ['React.js', 'Chart.js', 'D3.js'],
    github: 'https://github.com/etk18',
    category: 'Frontend',
  },
  {
    title: 'ML Model Deployment API',
    description: 'RESTful API service for deploying machine learning models with Docker.',
    tags: ['Python', 'Flask', 'Docker'],
    github: 'https://github.com/etk18',
    category: 'Backend',
  },
  {
    title: 'Portfolio Website',
    description: 'Modern, animated portfolio with AI-powered chatbot assistant.',
    tags: ['React.js', 'Framer Motion', 'Three.js'],
    github: 'https://github.com/etk18',
    category: 'Frontend',
  },
];

/* ============================================================
   SUB-COMPONENTS
   ============================================================ */

/** Single architectural highlight row — expandable on click */
const HighlightItem = ({ highlight, index, accentClass }) => {
  const [open, setOpen] = useState(false);
  const Icon = highlight.icon;

  return (
    <motion.button
      onClick={() => setOpen((v) => !v)}
      className={`w-full text-left group/hi focus:outline-none`}
      initial={{ opacity: 0, x: -20 }}
      whileInView={{ opacity: 1, x: 0 }}
      viewport={{ once: true }}
      transition={{ duration: 0.4, delay: index * 0.08 }}
    >
      <div className="flex items-start gap-4 p-4 rounded-xl bg-[var(--bg-secondary)]/60 border border-[var(--border-color)] hover:border-rose-500/30 transition-all bento-highlight">
        {/* icon */}
        <div className={`shrink-0 p-2.5 rounded-lg ${accentClass === 'onyx' ? 'bg-sky-500/10 text-sky-400' : 'bg-emerald-500/10 text-emerald-400'}`}>
          <Icon size={18} />
        </div>

        {/* text */}
        <div className="flex-1 min-w-0">
          <div className="flex items-center justify-between gap-2">
            <h4 className="text-sm font-semibold text-[var(--text-primary)] group-hover/hi:text-rose-400 transition-colors">
              {highlight.title}
            </h4>
            <ChevronDown
              size={14}
              className={`shrink-0 text-[var(--text-muted)] transition-transform duration-300 ${open ? 'rotate-180' : ''}`}
            />
          </div>
          <AnimatePresence initial={false}>
            {open && (
              <motion.p
                initial={{ height: 0, opacity: 0 }}
                animate={{ height: 'auto', opacity: 1 }}
                exit={{ height: 0, opacity: 0 }}
                transition={{ duration: 0.25 }}
                className="text-[var(--text-muted)] text-xs leading-relaxed mt-2 overflow-hidden"
              >
                {highlight.detail}
              </motion.p>
            )}
          </AnimatePresence>
        </div>
      </div>
    </motion.button>
  );
};

/** Full bento case-study card */
const CaseStudyCard = ({ project, index }) => {
  const Icon = project.icon;
  const isOnyx = project.accent === 'onyx';

  const accentGradient = isOnyx
    ? 'from-sky-500 via-indigo-500 to-violet-600'
    : 'from-emerald-400 via-teal-500 to-cyan-600';

  const accentGlow = isOnyx ? 'sky-500' : 'emerald-500';

  return (
    <motion.div
      initial={{ opacity: 0, y: 60 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, margin: '-80px' }}
      transition={{ duration: 0.7, delay: index * 0.15 }}
      className="relative group"
    >
      {/* Glow backdrop */}
      <div
        className={`absolute -inset-0.5 rounded-2xl bg-gradient-to-r ${accentGradient} opacity-0 group-hover:opacity-20 blur-xl transition-opacity duration-700`}
      />

      <GlassCard className="relative p-0 overflow-hidden">
        {/* Accent top bar */}
        <div className={`h-1 w-full bg-gradient-to-r ${accentGradient} case-study-shimmer`} />

        <div className="p-6 sm:p-8 lg:p-10">
          {/* Header row */}
          <div className="flex flex-col sm:flex-row sm:items-center gap-4 mb-6">
            <div className={`p-3 rounded-xl bg-gradient-to-br ${accentGradient} bg-opacity-10 shrink-0 w-fit`}>
              <Icon size={28} className="text-white" />
            </div>
            <div className="flex-1 min-w-0">
              <div className="flex items-center gap-2 flex-wrap">
                <h3 className="text-2xl sm:text-3xl font-bold text-[var(--text-primary)]">
                  {project.title}
                </h3>
                <span className={`px-2.5 py-0.5 text-xs font-medium rounded-full bg-${accentGlow}/15 text-${accentGlow} border border-${accentGlow}/25 flex items-center gap-1`}>
                  <Sparkles size={10} />
                  Flagship
                </span>
              </div>
              <p className={`text-sm font-medium mt-1 ${isOnyx ? 'text-sky-400' : 'text-emerald-400'}`}>
                {project.subtitle}
              </p>
            </div>
          </div>

          {/* Tech stack pills */}
          <div className="flex flex-wrap gap-2 mb-6">
            {project.stack.map((tech) => (
              <span
                key={tech}
                className={`px-3 py-1 text-xs font-medium rounded-full border ${isOnyx
                  ? 'border-sky-500/20 text-sky-300 bg-sky-500/5'
                  : 'border-emerald-500/20 text-emerald-300 bg-emerald-500/5'
                  }`}
              >
                {tech}
              </span>
            ))}
          </div>

          {/* Description */}
          <p className="text-[var(--text-secondary)] leading-relaxed mb-8 max-w-3xl">
            {project.description}
          </p>

          {/* Architectural Highlights */}
          <div className="mb-8">
            <div className="flex items-center gap-2 mb-4">
              <Layers size={16} className={isOnyx ? 'text-sky-400' : 'text-emerald-400'} />
              <h4 className="text-sm font-semibold text-[var(--text-primary)] tracking-wide uppercase">
                Architectural Highlights
              </h4>
            </div>
            <div className="grid gap-3 sm:grid-cols-2">
              {project.highlights.map((h, i) => (
                <HighlightItem
                  key={h.title}
                  highlight={h}
                  index={i}
                  accentClass={project.accent}
                />
              ))}
            </div>
          </div>

          {/* CTA row */}
          <div className="flex items-center gap-4">
            <a
              href={project.github}
              target="_blank"
              rel="noopener noreferrer"
              className={`inline-flex items-center gap-2 px-5 py-2.5 text-sm font-semibold rounded-xl border transition-all ${isOnyx
                ? 'border-sky-500/30 text-sky-400 hover:bg-sky-500/10'
                : 'border-emerald-500/30 text-emerald-400 hover:bg-emerald-500/10'
                }`}
            >
              <Github size={16} />
              View Source
            </a>
            <a
              href={project.live}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 px-5 py-2.5 text-sm font-semibold rounded-xl text-[var(--text-muted)] hover:text-[var(--text-primary)] border border-[var(--border-color)] hover:border-rose-500/30 transition-all"
            >
              <ExternalLink size={16} />
              Live Demo
            </a>
          </div>
        </div>
      </GlassCard>
    </motion.div>
  );
};

/** Compact card for "Other Projects" */
const OtherProjectCard = ({ project, index }) => {
  return (
    <motion.div
      initial={{ opacity: 0, y: 30 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, margin: '-50px' }}
      transition={{ duration: 0.5, delay: index * 0.08 }}
    >
      <GlassCard className="p-6 h-full group hover:border-rose-500/30 transition-all">
        <div className="flex items-start justify-between mb-4">
          <div className="p-3 bg-[var(--bg-tertiary)] rounded-xl group-hover:bg-rose-500/10 transition-colors">
            <Folder className="text-[var(--text-muted)] group-hover:text-rose-400 transition-colors" size={24} />
          </div>
          <div className="flex gap-3 items-center">
            {project.status && (
              <span className="px-2 py-0.5 text-[10px] font-medium bg-amber-500/15 text-amber-400 rounded-full flex items-center gap-1">
                <Sparkles size={8} />
                {project.status}
              </span>
            )}
            <a
              href={project.github}
              target="_blank"
              rel="noopener noreferrer"
              className="text-[var(--text-muted)] hover:text-rose-400 transition-colors"
            >
              <Github size={18} />
            </a>
          </div>
        </div>

        <h3 className="text-lg font-bold text-[var(--text-primary)] mb-2 group-hover:text-rose-400 transition-colors">
          {project.title}
        </h3>

        <p className="text-[var(--text-muted)] text-sm mb-4 leading-relaxed line-clamp-3">
          {project.description}
        </p>

        <div className="flex flex-wrap gap-2 mt-auto">
          {project.tags.slice(0, 4).map((tag) => (
            <span
              key={tag}
              className="px-2 py-1 text-xs text-[var(--text-muted)] bg-[var(--bg-tertiary)] rounded"
            >
              {tag}
            </span>
          ))}
        </div>
      </GlassCard>
    </motion.div>
  );
};

/* ============================================================
   MAIN COMPONENT
   ============================================================ */

const Projects = () => {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, margin: '-100px' });

  return (
    <section id="projects" className="py-24 md:py-32 relative overflow-hidden">
      {/* Background blurs */}
      <div className="absolute inset-0 overflow-hidden">
        <div className="absolute top-1/4 right-0 w-[500px] h-[500px] bg-rose-500/5 rounded-full blur-[100px]" />
        <div className="absolute bottom-1/4 left-0 w-[400px] h-[400px] bg-amber-500/5 rounded-full blur-[100px]" />
        <div className="absolute top-1/2 left-1/3 w-[350px] h-[350px] bg-sky-500/5 rounded-full blur-[120px]" />
      </div>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10" ref={ref}>
        {/* Section Header */}
        <motion.div
          className="mb-16"
          initial={{ opacity: 0, y: 30 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.6 }}
        >
          <div className="flex items-center gap-4 mb-4">
            <span className="text-rose-400 font-medium text-sm tracking-wider uppercase">Portfolio</span>
            <div className="h-px flex-1 max-w-[100px] bg-gradient-to-r from-rose-500 to-transparent" />
          </div>
          <h2 className="text-4xl sm:text-5xl md:text-6xl font-bold text-[var(--text-primary)]">
            Featured <span className="text-gradient">Case Studies</span>
          </h2>
          <p className="mt-4 text-[var(--text-muted)] max-w-2xl text-lg">
            Deep-dive engineering breakdowns of my flagship projects — exploring system architecture, design decisions, and technical problem-solving.
          </p>
        </motion.div>

        {/* ── Flagship Case Studies ── */}
        <div className="grid gap-10 lg:gap-12 mb-28">
          {flagshipProjects.map((project, index) => (
            <CaseStudyCard key={project.id} project={project} index={index} />
          ))}
        </div>

        {/* ── Other Projects ── */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="mb-10"
        >
          <div className="flex items-center gap-4 mb-2">
            <Terminal size={18} className="text-rose-400" />
            <h3 className="text-2xl font-bold text-[var(--text-primary)]">
              Other Projects
            </h3>
          </div>
          <p className="text-[var(--text-muted)] text-sm">
            Additional work across AI/ML, full-stack, and frontend engineering.
          </p>
        </motion.div>

        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {otherProjects.map((project, index) => (
            <OtherProjectCard key={project.title} project={project} index={index} />
          ))}
        </div>
      </div>
    </section>
  );
};

export default Projects;
